version: '2'
services:
  www:
    build: ./docker/www
    ports:
      - 8080:80
    volumes_from:
      - fpm
    links:
      - fpm
  fpm:
    build: ./
    volumes:
      - .:/var/www
    working_dir: /var/www
    links:
      - db
  db:
    image: mysql
    command: ['--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci','--default-authentication-plugin=mysql_native_password']
    environment:
        - MYSQL_ROOT_PASSWORD=user
        - MYSQL_DATABASE=recruitment
        - MYSQL_USER=user
        - MYSQL_PASSWORD=user
